vti_encoding:SR|utf8-nl
vti_author:SR|ZHANGJING\\Administrator
vti_modifiedby:SR|ZHANGJING\\Administrator
vti_timelastmodified:TR|11 Sep 2007 03:16:07 -0000
vti_timecreated:TR|11 Sep 2007 03:16:07 -0000
vti_cacheddtm:TX|11 Sep 2007 03:16:07 -0000
vti_filesize:IR|5737
vti_extenderversion:SR|12.0.0.4518
vti_backlinkinfo:VX|views/setup/dictionary/dynamicTaskList.html views/setup/keyEventEvalStandard/edit.html views/setup/interface/edit.html views/setup/routineTask/edit.html views/setup/routineTask/index.html views/setup/measurementtable/edit.html views/examinationDefinition/dynamicTask/index.html views/taskAllocation/routineTask/editIndividualTask.html views/taskAllocation/routineTask/editDepartTask.html views/setup/measurementtable/index.html views/setup/taskEvalStandard/edit.html views/setup/organization/index.html views/examinationDefinition/serviceTarget/edit.html views/setup/dictionary/dynamicTaskLevelList.html views/setup/interface/index.html views/examinationDefinition/routineTask/index.html views/examinationDefinition/dynamicTask/edit.html views/examinationDefinition/individualQuality/index.html views/examinationDefinition/individualQuality/edit.html views/setup/examinationStandard/index.html views/setup/dictionary/routineTaskCategoryList.html views/examinationDefinition/keyEvent/edit.html views/examinationDefinition/serviceTarget/index.html views/setup/permission/index.html views/setup/dictionary/keyEventList.html views/setup/dictionary/informationSourceList.html views/setup/dictionary/validityLevelList.html views/examinationDefinition/keyEvent/index.html views/examinationDefinition/mutualReview/index.html views/taskAllocation/dynamicTask/index.html views/setup/permission/edit.html views/setup/dictionary/universalTaskCategoryList.html views/setup/dictionary/agePowerList.html views/setup/yearlyExamination/index.html views/setup/yearlyExamination/edit.html views/setup/taskEvalStandard/index.html views/examinationDefinition/mutualReview/edit.html views/taskAllocation/routineTask/index.html views/taskAllocation/dynamicTask/editIndividualTask.html views/setup/keyEventEvalStandard/index.html views/taskAllocation/dynamicTask/editDepartTask.html views/setup/user/edit.html views/setup/user/index.html views/setup/dictionary/reliabilityLevelList.html views/setup/dictionary/kpiIndexList.html
