vti_encoding:SR|utf8-nl
vti_author:SR|ZHANGJING\\Administrator
vti_modifiedby:SR|ZHANGJING\\Administrator
vti_timelastmodified:TR|10 Sep 2007 06:42:28 -0000
vti_timecreated:TR|10 Sep 2007 05:48:20 -0000
vti_extenderversion:SR|12.0.0.4518
vti_backlinkinfo:VX|views/setup/keyEventEvalStandard/edit.html views/setup/dictionary/dynamicTaskList.html views/examination/staffManagement/index.html views/examination/examQuery/index.html views/examinationDefinition/dynamicTask/index.html views/taskAllocation/routineTask/editIndividualTask.html views/taskAllocation/routineTask/editDepartTask.html views/setup/routineTask/edit.html views/setup/routineTask/index.html views/examinationDefinition/serviceTarget/edit.html views/setup/organization/index.html views/setup/taskEvalStandard/edit.html views/examination/yearlyExam/individualDetail.html views/examinationDefinition/dynamicTask/edit.html views/examinationDefinition/individualQuality/edit.html views/examinationDefinition/individualQuality/index.html views/examinationDefinition/routineTask/index.html views/setup/interface/index.html views/setup/dictionary/dynamicTaskLevelList.html views/examination/mutualReviewQuery/index.html views/examinationDefinition/keyEvent/edit.html views/examinationDefinition/serviceTarget/index.html views/setup/examinationStandard/index.html views/setup/dictionary/routineTaskCategoryList.html views/examination/monthlyExam/index.html views/examination/windowManagement/index.html views/examination/yearlyExam/index.html views/examinationDefinition/keyEvent/index.html views/examinationDefinition/mutualReview/index.html views/taskAllocation/dynamicTask/index.html views/setup/permission/index.html views/setup/dictionary/informationSourceList.html views/setup/dictionary/keyEventList.html views/setup/dictionary/validityLevelList.html views/examinationDefinition/mutualReview/edit.html views/taskAllocation/routineTask/index.html views/taskAllocation/dynamicTask/editIndividualTask.html views/setup/permission/edit.html views/setup/taskEvalStandard/index.html views/setup/yearlyExamination/edit.html views/setup/yearlyExamination/index.html views/setup/dictionary/agePowerList.html views/setup/dictionary/universalTaskCategoryList.html views/examination/weeklyEval/index.html views/taskAllocation/dynamicTask/editDepartTask.html views/setup/keyEventEvalStandard/index.html views/setup/user/edit.html views/setup/user/index.html views/setup/dictionary/kpiIndexList.html views/setup/dictionary/reliabilityLevelList.html views/examination/weeklySumUpQuery/index.html views/examination/yearlyExam/yearlyDetail.html views/setup/interface/edit.html views/setup/measurementtable/edit.html views/setup/measurementtable/index.html
vti_cacheddtm:TX|10 Sep 2007 05:48:20 -0000
vti_filesize:IR|5820
vti_nexttolasttimemodified:TR|10 Sep 2007 05:48:20 -0000
